using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DAL{
    /// <summary>
    /// Strongly-typed collection for the ActiveEstimateForReporting class.
    /// </summary>
    [Serializable]
    public partial class ActiveEstimateForReportingCollection : ReadOnlyList<ActiveEstimateForReporting, ActiveEstimateForReportingCollection>
    {        
        public ActiveEstimateForReportingCollection() {}
    }
    /// <summary>
    /// This is  Read-only wrapper class for the ActiveEstimateForReporting view.
    /// </summary>
    [Serializable]
    public partial class ActiveEstimateForReporting : ReadOnlyRecord<ActiveEstimateForReporting>, IReadOnlyRecord
    {
    
	    #region Default Settings
	    protected static void SetSQLProps() 
	    {
		    GetTableSchema();
	    }
	    #endregion
        #region Schema Accessor
	    public static TableSchema.Table Schema
        {
            get
            {
                if (BaseSchema == null)
                {
                    SetSQLProps();
                }
                return BaseSchema;
            }
        }
    	
        private static void GetTableSchema() 
        {
            if(!IsSchemaInitialized)
            {
                //Schema declaration
                TableSchema.Table schema = new TableSchema.Table("ActiveEstimateForReporting", TableType.View, DataService.GetInstance("Internal"));
                schema.Columns = new TableSchema.TableColumnCollection();
                schema.SchemaName = @"dbo";
                //columns
                
                TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
                colvarId.ColumnName = "ID";
                colvarId.DataType = DbType.Int32;
                colvarId.MaxLength = 0;
                colvarId.AutoIncrement = false;
                colvarId.IsNullable = false;
                colvarId.IsPrimaryKey = false;
                colvarId.IsForeignKey = false;
                colvarId.IsReadOnly = false;
                
                schema.Columns.Add(colvarId);
                
                TableSchema.TableColumn colvarEstimateNumber = new TableSchema.TableColumn(schema);
                colvarEstimateNumber.ColumnName = "EstimateNumber";
                colvarEstimateNumber.DataType = DbType.AnsiString;
                colvarEstimateNumber.MaxLength = 50;
                colvarEstimateNumber.AutoIncrement = false;
                colvarEstimateNumber.IsNullable = true;
                colvarEstimateNumber.IsPrimaryKey = false;
                colvarEstimateNumber.IsForeignKey = false;
                colvarEstimateNumber.IsReadOnly = false;
                
                schema.Columns.Add(colvarEstimateNumber);
                
                TableSchema.TableColumn colvarProjectName = new TableSchema.TableColumn(schema);
                colvarProjectName.ColumnName = "ProjectName";
                colvarProjectName.DataType = DbType.AnsiString;
                colvarProjectName.MaxLength = 100;
                colvarProjectName.AutoIncrement = false;
                colvarProjectName.IsNullable = false;
                colvarProjectName.IsPrimaryKey = false;
                colvarProjectName.IsForeignKey = false;
                colvarProjectName.IsReadOnly = false;
                
                schema.Columns.Add(colvarProjectName);
                
                TableSchema.TableColumn colvarAction = new TableSchema.TableColumn(schema);
                colvarAction.ColumnName = "Action";
                colvarAction.DataType = DbType.AnsiString;
                colvarAction.MaxLength = 50;
                colvarAction.AutoIncrement = false;
                colvarAction.IsNullable = false;
                colvarAction.IsPrimaryKey = false;
                colvarAction.IsForeignKey = false;
                colvarAction.IsReadOnly = false;
                
                schema.Columns.Add(colvarAction);
                
                TableSchema.TableColumn colvarDateTimeStamp = new TableSchema.TableColumn(schema);
                colvarDateTimeStamp.ColumnName = "DateTimeStamp";
                colvarDateTimeStamp.DataType = DbType.DateTime;
                colvarDateTimeStamp.MaxLength = 0;
                colvarDateTimeStamp.AutoIncrement = false;
                colvarDateTimeStamp.IsNullable = false;
                colvarDateTimeStamp.IsPrimaryKey = false;
                colvarDateTimeStamp.IsForeignKey = false;
                colvarDateTimeStamp.IsReadOnly = false;
                
                schema.Columns.Add(colvarDateTimeStamp);
                
                
                BaseSchema = schema;
                //add this schema to the provider
                //so we can query it later
                DataService.Providers["Internal"].AddSchema("ActiveEstimateForReporting",schema);
            }
        }
        #endregion
        
        #region Query Accessor
	    public static Query CreateQuery()
	    {
		    return new Query(Schema);
	    }
	    #endregion
	    
	    #region .ctors
	    public ActiveEstimateForReporting()
	    {
            SetSQLProps();
            SetDefaults();
            MarkNew();
        }
        public ActiveEstimateForReporting(bool useDatabaseDefaults)
	    {
		    SetSQLProps();
		    if(useDatabaseDefaults)
		    {
				ForceDefaults();
			}
			MarkNew();
	    }
	    
	    public ActiveEstimateForReporting(object keyID)
	    {
		    SetSQLProps();
		    LoadByKey(keyID);
	    }
    	 
	    public ActiveEstimateForReporting(string columnName, object columnValue)
        {
            SetSQLProps();
            LoadByParam(columnName,columnValue);
        }
        
	    #endregion
	    
	    #region Props
	    
          
        [XmlAttribute("Id")]
        [Bindable(true)]
        public int Id 
	    {
		    get
		    {
			    return GetColumnValue<int>("ID");
		    }
            set 
		    {
			    SetColumnValue("ID", value);
            }
        }
	      
        [XmlAttribute("EstimateNumber")]
        [Bindable(true)]
        public string EstimateNumber 
	    {
		    get
		    {
			    return GetColumnValue<string>("EstimateNumber");
		    }
            set 
		    {
			    SetColumnValue("EstimateNumber", value);
            }
        }
	      
        [XmlAttribute("ProjectName")]
        [Bindable(true)]
        public string ProjectName 
	    {
		    get
		    {
			    return GetColumnValue<string>("ProjectName");
		    }
            set 
		    {
			    SetColumnValue("ProjectName", value);
            }
        }
	      
        [XmlAttribute("Action")]
        [Bindable(true)]
        public string Action 
	    {
		    get
		    {
			    return GetColumnValue<string>("Action");
		    }
            set 
		    {
			    SetColumnValue("Action", value);
            }
        }
	      
        [XmlAttribute("DateTimeStamp")]
        [Bindable(true)]
        public DateTime DateTimeStamp 
	    {
		    get
		    {
			    return GetColumnValue<DateTime>("DateTimeStamp");
		    }
            set 
		    {
			    SetColumnValue("DateTimeStamp", value);
            }
        }
	    
	    #endregion
    
	    #region Columns Struct
	    public struct Columns
	    {
		    
		    
            public static string Id = @"ID";
            
            public static string EstimateNumber = @"EstimateNumber";
            
            public static string ProjectName = @"ProjectName";
            
            public static string Action = @"Action";
            
            public static string DateTimeStamp = @"DateTimeStamp";
            
	    }
	    #endregion
	    
	    
	    #region IAbstractRecord Members
        public new CT GetColumnValue<CT>(string columnName) {
            return base.GetColumnValue<CT>(columnName);
        }
        public object GetColumnValue(string columnName) {
            return base.GetColumnValue<object>(columnName);
        }
        #endregion
	    
    }
}
