using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DAL{
    /// <summary>
    /// Strongly-typed collection for the ActiveEstimatesWithNoActivityLastWeek class.
    /// </summary>
    [Serializable]
    public partial class ActiveEstimatesWithNoActivityLastWeekCollection : ReadOnlyList<ActiveEstimatesWithNoActivityLastWeek, ActiveEstimatesWithNoActivityLastWeekCollection>
    {        
        public ActiveEstimatesWithNoActivityLastWeekCollection() {}
    }
    /// <summary>
    /// This is  Read-only wrapper class for the ActiveEstimatesWithNoActivityLastWeek view.
    /// </summary>
    [Serializable]
    public partial class ActiveEstimatesWithNoActivityLastWeek : ReadOnlyRecord<ActiveEstimatesWithNoActivityLastWeek>, IReadOnlyRecord
    {
    
	    #region Default Settings
	    protected static void SetSQLProps() 
	    {
		    GetTableSchema();
	    }
	    #endregion
        #region Schema Accessor
	    public static TableSchema.Table Schema
        {
            get
            {
                if (BaseSchema == null)
                {
                    SetSQLProps();
                }
                return BaseSchema;
            }
        }
    	
        private static void GetTableSchema() 
        {
            if(!IsSchemaInitialized)
            {
                //Schema declaration
                TableSchema.Table schema = new TableSchema.Table("ActiveEstimatesWithNoActivityLastWeek", TableType.View, DataService.GetInstance("Internal"));
                schema.Columns = new TableSchema.TableColumnCollection();
                schema.SchemaName = @"dbo";
                //columns
                
                TableSchema.TableColumn colvarReceived = new TableSchema.TableColumn(schema);
                colvarReceived.ColumnName = "Received";
                colvarReceived.DataType = DbType.DateTime;
                colvarReceived.MaxLength = 0;
                colvarReceived.AutoIncrement = false;
                colvarReceived.IsNullable = true;
                colvarReceived.IsPrimaryKey = false;
                colvarReceived.IsForeignKey = false;
                colvarReceived.IsReadOnly = false;
                
                schema.Columns.Add(colvarReceived);
                
                TableSchema.TableColumn colvarDisplayText = new TableSchema.TableColumn(schema);
                colvarDisplayText.ColumnName = "DisplayText";
                colvarDisplayText.DataType = DbType.AnsiString;
                colvarDisplayText.MaxLength = 203;
                colvarDisplayText.AutoIncrement = false;
                colvarDisplayText.IsNullable = false;
                colvarDisplayText.IsPrimaryKey = false;
                colvarDisplayText.IsForeignKey = false;
                colvarDisplayText.IsReadOnly = false;
                
                schema.Columns.Add(colvarDisplayText);
                
                TableSchema.TableColumn colvarEstimatorName = new TableSchema.TableColumn(schema);
                colvarEstimatorName.ColumnName = "EstimatorName";
                colvarEstimatorName.DataType = DbType.AnsiString;
                colvarEstimatorName.MaxLength = 50;
                colvarEstimatorName.AutoIncrement = false;
                colvarEstimatorName.IsNullable = true;
                colvarEstimatorName.IsPrimaryKey = false;
                colvarEstimatorName.IsForeignKey = false;
                colvarEstimatorName.IsReadOnly = false;
                
                schema.Columns.Add(colvarEstimatorName);
                
                TableSchema.TableColumn colvarCurrentStatus = new TableSchema.TableColumn(schema);
                colvarCurrentStatus.ColumnName = "CurrentStatus";
                colvarCurrentStatus.DataType = DbType.AnsiString;
                colvarCurrentStatus.MaxLength = -1;
                colvarCurrentStatus.AutoIncrement = false;
                colvarCurrentStatus.IsNullable = true;
                colvarCurrentStatus.IsPrimaryKey = false;
                colvarCurrentStatus.IsForeignKey = false;
                colvarCurrentStatus.IsReadOnly = false;
                
                schema.Columns.Add(colvarCurrentStatus);
                
                TableSchema.TableColumn colvarAction = new TableSchema.TableColumn(schema);
                colvarAction.ColumnName = "Action";
                colvarAction.DataType = DbType.AnsiString;
                colvarAction.MaxLength = 50;
                colvarAction.AutoIncrement = false;
                colvarAction.IsNullable = false;
                colvarAction.IsPrimaryKey = false;
                colvarAction.IsForeignKey = false;
                colvarAction.IsReadOnly = false;
                
                schema.Columns.Add(colvarAction);
                
                
                BaseSchema = schema;
                //add this schema to the provider
                //so we can query it later
                DataService.Providers["Internal"].AddSchema("ActiveEstimatesWithNoActivityLastWeek",schema);
            }
        }
        #endregion
        
        #region Query Accessor
	    public static Query CreateQuery()
	    {
		    return new Query(Schema);
	    }
	    #endregion
	    
	    #region .ctors
	    public ActiveEstimatesWithNoActivityLastWeek()
	    {
            SetSQLProps();
            SetDefaults();
            MarkNew();
        }
        public ActiveEstimatesWithNoActivityLastWeek(bool useDatabaseDefaults)
	    {
		    SetSQLProps();
		    if(useDatabaseDefaults)
		    {
				ForceDefaults();
			}
			MarkNew();
	    }
	    
	    public ActiveEstimatesWithNoActivityLastWeek(object keyID)
	    {
		    SetSQLProps();
		    LoadByKey(keyID);
	    }
    	 
	    public ActiveEstimatesWithNoActivityLastWeek(string columnName, object columnValue)
        {
            SetSQLProps();
            LoadByParam(columnName,columnValue);
        }
        
	    #endregion
	    
	    #region Props
	    
          
        [XmlAttribute("Received")]
        [Bindable(true)]
        public DateTime? Received 
	    {
		    get
		    {
			    return GetColumnValue<DateTime?>("Received");
		    }
            set 
		    {
			    SetColumnValue("Received", value);
            }
        }
	      
        [XmlAttribute("DisplayText")]
        [Bindable(true)]
        public string DisplayText 
	    {
		    get
		    {
			    return GetColumnValue<string>("DisplayText");
		    }
            set 
		    {
			    SetColumnValue("DisplayText", value);
            }
        }
	      
        [XmlAttribute("EstimatorName")]
        [Bindable(true)]
        public string EstimatorName 
	    {
		    get
		    {
			    return GetColumnValue<string>("EstimatorName");
		    }
            set 
		    {
			    SetColumnValue("EstimatorName", value);
            }
        }
	      
        [XmlAttribute("CurrentStatus")]
        [Bindable(true)]
        public string CurrentStatus 
	    {
		    get
		    {
			    return GetColumnValue<string>("CurrentStatus");
		    }
            set 
		    {
			    SetColumnValue("CurrentStatus", value);
            }
        }
	      
        [XmlAttribute("Action")]
        [Bindable(true)]
        public string Action 
	    {
		    get
		    {
			    return GetColumnValue<string>("Action");
		    }
            set 
		    {
			    SetColumnValue("Action", value);
            }
        }
	    
	    #endregion
    
	    #region Columns Struct
	    public struct Columns
	    {
		    
		    
            public static string Received = @"Received";
            
            public static string DisplayText = @"DisplayText";
            
            public static string EstimatorName = @"EstimatorName";
            
            public static string CurrentStatus = @"CurrentStatus";
            
            public static string Action = @"Action";
            
	    }
	    #endregion
	    
	    
	    #region IAbstractRecord Members
        public new CT GetColumnValue<CT>(string columnName) {
            return base.GetColumnValue<CT>(columnName);
        }
        public object GetColumnValue(string columnName) {
            return base.GetColumnValue<object>(columnName);
        }
        #endregion
	    
    }
}
