using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DAL{
    /// <summary>
    /// Strongly-typed collection for the ActiveProject class.
    /// </summary>
    [Serializable]
    public partial class ActiveProjectCollection : ReadOnlyList<ActiveProject, ActiveProjectCollection>
    {        
        public ActiveProjectCollection() {}
    }
    /// <summary>
    /// This is  Read-only wrapper class for the ActiveProjects view.
    /// </summary>
    [Serializable]
    public partial class ActiveProject : ReadOnlyRecord<ActiveProject>, IReadOnlyRecord
    {
    
	    #region Default Settings
	    protected static void SetSQLProps() 
	    {
		    GetTableSchema();
	    }
	    #endregion
        #region Schema Accessor
	    public static TableSchema.Table Schema
        {
            get
            {
                if (BaseSchema == null)
                {
                    SetSQLProps();
                }
                return BaseSchema;
            }
        }
    	
        private static void GetTableSchema() 
        {
            if(!IsSchemaInitialized)
            {
                //Schema declaration
                TableSchema.Table schema = new TableSchema.Table("ActiveProjects", TableType.View, DataService.GetInstance("Internal"));
                schema.Columns = new TableSchema.TableColumnCollection();
                schema.SchemaName = @"dbo";
                //columns
                
                TableSchema.TableColumn colvarProject = new TableSchema.TableColumn(schema);
                colvarProject.ColumnName = "Project";
                colvarProject.DataType = DbType.AnsiString;
                colvarProject.MaxLength = 203;
                colvarProject.AutoIncrement = false;
                colvarProject.IsNullable = false;
                colvarProject.IsPrimaryKey = false;
                colvarProject.IsForeignKey = false;
                colvarProject.IsReadOnly = false;
                
                schema.Columns.Add(colvarProject);
                
                TableSchema.TableColumn colvarAssignedPM = new TableSchema.TableColumn(schema);
                colvarAssignedPM.ColumnName = "AssignedPM";
                colvarAssignedPM.DataType = DbType.AnsiString;
                colvarAssignedPM.MaxLength = 50;
                colvarAssignedPM.AutoIncrement = false;
                colvarAssignedPM.IsNullable = true;
                colvarAssignedPM.IsPrimaryKey = false;
                colvarAssignedPM.IsForeignKey = false;
                colvarAssignedPM.IsReadOnly = false;
                
                schema.Columns.Add(colvarAssignedPM);
                
                TableSchema.TableColumn colvarDraftsman = new TableSchema.TableColumn(schema);
                colvarDraftsman.ColumnName = "Draftsman";
                colvarDraftsman.DataType = DbType.AnsiString;
                colvarDraftsman.MaxLength = 50;
                colvarDraftsman.AutoIncrement = false;
                colvarDraftsman.IsNullable = true;
                colvarDraftsman.IsPrimaryKey = false;
                colvarDraftsman.IsForeignKey = false;
                colvarDraftsman.IsReadOnly = false;
                
                schema.Columns.Add(colvarDraftsman);
                
                TableSchema.TableColumn colvarSalesman = new TableSchema.TableColumn(schema);
                colvarSalesman.ColumnName = "Salesman";
                colvarSalesman.DataType = DbType.AnsiString;
                colvarSalesman.MaxLength = 50;
                colvarSalesman.AutoIncrement = false;
                colvarSalesman.IsNullable = true;
                colvarSalesman.IsPrimaryKey = false;
                colvarSalesman.IsForeignKey = false;
                colvarSalesman.IsReadOnly = false;
                
                schema.Columns.Add(colvarSalesman);
                
                TableSchema.TableColumn colvarEngineeringConsultant = new TableSchema.TableColumn(schema);
                colvarEngineeringConsultant.ColumnName = "EngineeringConsultant";
                colvarEngineeringConsultant.DataType = DbType.AnsiString;
                colvarEngineeringConsultant.MaxLength = 100;
                colvarEngineeringConsultant.AutoIncrement = false;
                colvarEngineeringConsultant.IsNullable = true;
                colvarEngineeringConsultant.IsPrimaryKey = false;
                colvarEngineeringConsultant.IsForeignKey = false;
                colvarEngineeringConsultant.IsReadOnly = false;
                
                schema.Columns.Add(colvarEngineeringConsultant);
                
                TableSchema.TableColumn colvarPhysicist = new TableSchema.TableColumn(schema);
                colvarPhysicist.ColumnName = "Physicist";
                colvarPhysicist.DataType = DbType.AnsiString;
                colvarPhysicist.MaxLength = 50;
                colvarPhysicist.AutoIncrement = false;
                colvarPhysicist.IsNullable = true;
                colvarPhysicist.IsPrimaryKey = false;
                colvarPhysicist.IsForeignKey = false;
                colvarPhysicist.IsReadOnly = false;
                
                schema.Columns.Add(colvarPhysicist);
                
                TableSchema.TableColumn colvarProjectYear = new TableSchema.TableColumn(schema);
                colvarProjectYear.ColumnName = "ProjectYear";
                colvarProjectYear.DataType = DbType.AnsiString;
                colvarProjectYear.MaxLength = 2;
                colvarProjectYear.AutoIncrement = false;
                colvarProjectYear.IsNullable = true;
                colvarProjectYear.IsPrimaryKey = false;
                colvarProjectYear.IsForeignKey = false;
                colvarProjectYear.IsReadOnly = false;
                
                schema.Columns.Add(colvarProjectYear);
                
                TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
                colvarId.ColumnName = "ID";
                colvarId.DataType = DbType.Int32;
                colvarId.MaxLength = 0;
                colvarId.AutoIncrement = false;
                colvarId.IsNullable = false;
                colvarId.IsPrimaryKey = false;
                colvarId.IsForeignKey = false;
                colvarId.IsReadOnly = false;
                
                schema.Columns.Add(colvarId);
                
                TableSchema.TableColumn colvarProjectNumber = new TableSchema.TableColumn(schema);
                colvarProjectNumber.ColumnName = "ProjectNumber";
                colvarProjectNumber.DataType = DbType.AnsiString;
                colvarProjectNumber.MaxLength = 100;
                colvarProjectNumber.AutoIncrement = false;
                colvarProjectNumber.IsNullable = false;
                colvarProjectNumber.IsPrimaryKey = false;
                colvarProjectNumber.IsForeignKey = false;
                colvarProjectNumber.IsReadOnly = false;
                
                schema.Columns.Add(colvarProjectNumber);
                
                
                BaseSchema = schema;
                //add this schema to the provider
                //so we can query it later
                DataService.Providers["Internal"].AddSchema("ActiveProjects",schema);
            }
        }
        #endregion
        
        #region Query Accessor
	    public static Query CreateQuery()
	    {
		    return new Query(Schema);
	    }
	    #endregion
	    
	    #region .ctors
	    public ActiveProject()
	    {
            SetSQLProps();
            SetDefaults();
            MarkNew();
        }
        public ActiveProject(bool useDatabaseDefaults)
	    {
		    SetSQLProps();
		    if(useDatabaseDefaults)
		    {
				ForceDefaults();
			}
			MarkNew();
	    }
	    
	    public ActiveProject(object keyID)
	    {
		    SetSQLProps();
		    LoadByKey(keyID);
	    }
    	 
	    public ActiveProject(string columnName, object columnValue)
        {
            SetSQLProps();
            LoadByParam(columnName,columnValue);
        }
        
	    #endregion
	    
	    #region Props
	    
          
        [XmlAttribute("Project")]
        [Bindable(true)]
        public string Project 
	    {
		    get
		    {
			    return GetColumnValue<string>("Project");
		    }
            set 
		    {
			    SetColumnValue("Project", value);
            }
        }
	      
        [XmlAttribute("AssignedPM")]
        [Bindable(true)]
        public string AssignedPM 
	    {
		    get
		    {
			    return GetColumnValue<string>("AssignedPM");
		    }
            set 
		    {
			    SetColumnValue("AssignedPM", value);
            }
        }
	      
        [XmlAttribute("Draftsman")]
        [Bindable(true)]
        public string Draftsman 
	    {
		    get
		    {
			    return GetColumnValue<string>("Draftsman");
		    }
            set 
		    {
			    SetColumnValue("Draftsman", value);
            }
        }
	      
        [XmlAttribute("Salesman")]
        [Bindable(true)]
        public string Salesman 
	    {
		    get
		    {
			    return GetColumnValue<string>("Salesman");
		    }
            set 
		    {
			    SetColumnValue("Salesman", value);
            }
        }
	      
        [XmlAttribute("EngineeringConsultant")]
        [Bindable(true)]
        public string EngineeringConsultant 
	    {
		    get
		    {
			    return GetColumnValue<string>("EngineeringConsultant");
		    }
            set 
		    {
			    SetColumnValue("EngineeringConsultant", value);
            }
        }
	      
        [XmlAttribute("Physicist")]
        [Bindable(true)]
        public string Physicist 
	    {
		    get
		    {
			    return GetColumnValue<string>("Physicist");
		    }
            set 
		    {
			    SetColumnValue("Physicist", value);
            }
        }
	      
        [XmlAttribute("ProjectYear")]
        [Bindable(true)]
        public string ProjectYear 
	    {
		    get
		    {
			    return GetColumnValue<string>("ProjectYear");
		    }
            set 
		    {
			    SetColumnValue("ProjectYear", value);
            }
        }
	      
        [XmlAttribute("Id")]
        [Bindable(true)]
        public int Id 
	    {
		    get
		    {
			    return GetColumnValue<int>("ID");
		    }
            set 
		    {
			    SetColumnValue("ID", value);
            }
        }
	      
        [XmlAttribute("ProjectNumber")]
        [Bindable(true)]
        public string ProjectNumber 
	    {
		    get
		    {
			    return GetColumnValue<string>("ProjectNumber");
		    }
            set 
		    {
			    SetColumnValue("ProjectNumber", value);
            }
        }
	    
	    #endregion
    
	    #region Columns Struct
	    public struct Columns
	    {
		    
		    
            public static string Project = @"Project";
            
            public static string AssignedPM = @"AssignedPM";
            
            public static string Draftsman = @"Draftsman";
            
            public static string Salesman = @"Salesman";
            
            public static string EngineeringConsultant = @"EngineeringConsultant";
            
            public static string Physicist = @"Physicist";
            
            public static string ProjectYear = @"ProjectYear";
            
            public static string Id = @"ID";
            
            public static string ProjectNumber = @"ProjectNumber";
            
	    }
	    #endregion
	    
	    
	    #region IAbstractRecord Members
        public new CT GetColumnValue<CT>(string columnName) {
            return base.GetColumnValue<CT>(columnName);
        }
        public object GetColumnValue(string columnName) {
            return base.GetColumnValue<object>(columnName);
        }
        #endregion
	    
    }
}
