using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DAL
{
    /// <summary>
    /// Controller class for EstimateItems
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class EstimateItemController
    {
        // Preload our schema..
        EstimateItem thisSchemaLoad = new EstimateItem();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public EstimateItemCollection FetchAll()
        {
            EstimateItemCollection coll = new EstimateItemCollection();
            Query qry = new Query(EstimateItem.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public EstimateItemCollection FetchByID(object Id)
        {
            EstimateItemCollection coll = new EstimateItemCollection().Where("ID", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public EstimateItemCollection FetchByQuery(Query qry)
        {
            EstimateItemCollection coll = new EstimateItemCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (EstimateItem.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (EstimateItem.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int EstimateID,string ItemType,int Quantity,string Style,string DisplayText,string Size,string Entry,string Type)
	    {
		    EstimateItem item = new EstimateItem();
		    
            item.EstimateID = EstimateID;
            
            item.ItemType = ItemType;
            
            item.Quantity = Quantity;
            
            item.Style = Style;
            
            item.DisplayText = DisplayText;
            
            item.Size = Size;
            
            item.Entry = Entry;
            
            item.Type = Type;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,int EstimateID,string ItemType,int Quantity,string Style,string DisplayText,string Size,string Entry,string Type)
	    {
		    EstimateItem item = new EstimateItem();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.EstimateID = EstimateID;
				
			item.ItemType = ItemType;
				
			item.Quantity = Quantity;
				
			item.Style = Style;
				
			item.DisplayText = DisplayText;
				
			item.Size = Size;
				
			item.Entry = Entry;
				
			item.Type = Type;
				
	        item.Save(UserName);
	    }
    }
}
