using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DAL{
    /// <summary>
    /// Strongly-typed collection for the EstimateWorkflowDuration class.
    /// </summary>
    [Serializable]
    public partial class EstimateWorkflowDurationCollection : ReadOnlyList<EstimateWorkflowDuration, EstimateWorkflowDurationCollection>
    {        
        public EstimateWorkflowDurationCollection() {}
    }
    /// <summary>
    /// This is  Read-only wrapper class for the EstimateWorkflowDurations view.
    /// </summary>
    [Serializable]
    public partial class EstimateWorkflowDuration : ReadOnlyRecord<EstimateWorkflowDuration>, IReadOnlyRecord
    {
    
	    #region Default Settings
	    protected static void SetSQLProps() 
	    {
		    GetTableSchema();
	    }
	    #endregion
        #region Schema Accessor
	    public static TableSchema.Table Schema
        {
            get
            {
                if (BaseSchema == null)
                {
                    SetSQLProps();
                }
                return BaseSchema;
            }
        }
    	
        private static void GetTableSchema() 
        {
            if(!IsSchemaInitialized)
            {
                //Schema declaration
                TableSchema.Table schema = new TableSchema.Table("EstimateWorkflowDurations", TableType.View, DataService.GetInstance("Internal"));
                schema.Columns = new TableSchema.TableColumnCollection();
                schema.SchemaName = @"dbo";
                //columns
                
                TableSchema.TableColumn colvarAction = new TableSchema.TableColumn(schema);
                colvarAction.ColumnName = "Action";
                colvarAction.DataType = DbType.AnsiString;
                colvarAction.MaxLength = 50;
                colvarAction.AutoIncrement = false;
                colvarAction.IsNullable = false;
                colvarAction.IsPrimaryKey = false;
                colvarAction.IsForeignKey = false;
                colvarAction.IsReadOnly = false;
                
                schema.Columns.Add(colvarAction);
                
                TableSchema.TableColumn colvarAverageDuration = new TableSchema.TableColumn(schema);
                colvarAverageDuration.ColumnName = "AverageDuration";
                colvarAverageDuration.DataType = DbType.Int32;
                colvarAverageDuration.MaxLength = 0;
                colvarAverageDuration.AutoIncrement = false;
                colvarAverageDuration.IsNullable = true;
                colvarAverageDuration.IsPrimaryKey = false;
                colvarAverageDuration.IsForeignKey = false;
                colvarAverageDuration.IsReadOnly = false;
                
                schema.Columns.Add(colvarAverageDuration);
                
                
                BaseSchema = schema;
                //add this schema to the provider
                //so we can query it later
                DataService.Providers["Internal"].AddSchema("EstimateWorkflowDurations",schema);
            }
        }
        #endregion
        
        #region Query Accessor
	    public static Query CreateQuery()
	    {
		    return new Query(Schema);
	    }
	    #endregion
	    
	    #region .ctors
	    public EstimateWorkflowDuration()
	    {
            SetSQLProps();
            SetDefaults();
            MarkNew();
        }
        public EstimateWorkflowDuration(bool useDatabaseDefaults)
	    {
		    SetSQLProps();
		    if(useDatabaseDefaults)
		    {
				ForceDefaults();
			}
			MarkNew();
	    }
	    
	    public EstimateWorkflowDuration(object keyID)
	    {
		    SetSQLProps();
		    LoadByKey(keyID);
	    }
    	 
	    public EstimateWorkflowDuration(string columnName, object columnValue)
        {
            SetSQLProps();
            LoadByParam(columnName,columnValue);
        }
        
	    #endregion
	    
	    #region Props
	    
          
        [XmlAttribute("Action")]
        [Bindable(true)]
        public string Action 
	    {
		    get
		    {
			    return GetColumnValue<string>("Action");
		    }
            set 
		    {
			    SetColumnValue("Action", value);
            }
        }
	      
        [XmlAttribute("AverageDuration")]
        [Bindable(true)]
        public int? AverageDuration 
	    {
		    get
		    {
			    return GetColumnValue<int?>("AverageDuration");
		    }
            set 
		    {
			    SetColumnValue("AverageDuration", value);
            }
        }
	    
	    #endregion
    
	    #region Columns Struct
	    public struct Columns
	    {
		    
		    
            public static string Action = @"Action";
            
            public static string AverageDuration = @"AverageDuration";
            
	    }
	    #endregion
	    
	    
	    #region IAbstractRecord Members
        public new CT GetColumnValue<CT>(string columnName) {
            return base.GetColumnValue<CT>(columnName);
        }
        public object GetColumnValue(string columnName) {
            return base.GetColumnValue<object>(columnName);
        }
        #endregion
	    
    }
}
