using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DAL
{
    /// <summary>
    /// Controller class for L_PhysicsBasis
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class PhysicsBasiController
    {
        // Preload our schema..
        PhysicsBasi thisSchemaLoad = new PhysicsBasi();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public PhysicsBasiCollection FetchAll()
        {
            PhysicsBasiCollection coll = new PhysicsBasiCollection();
            Query qry = new Query(PhysicsBasi.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public PhysicsBasiCollection FetchByID(object Id)
        {
            PhysicsBasiCollection coll = new PhysicsBasiCollection().Where("ID", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public PhysicsBasiCollection FetchByQuery(Query qry)
        {
            PhysicsBasiCollection coll = new PhysicsBasiCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (PhysicsBasi.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (PhysicsBasi.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string Display,string TextX,string PublicValue,string ControlledValue)
	    {
		    PhysicsBasi item = new PhysicsBasi();
		    
            item.Display = Display;
            
            item.TextX = TextX;
            
            item.PublicValue = PublicValue;
            
            item.ControlledValue = ControlledValue;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,string Display,string TextX,string PublicValue,string ControlledValue)
	    {
		    PhysicsBasi item = new PhysicsBasi();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.Display = Display;
				
			item.TextX = TextX;
				
			item.PublicValue = PublicValue;
				
			item.ControlledValue = ControlledValue;
				
	        item.Save(UserName);
	    }
    }
}
