using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DAL
{
    /// <summary>
    /// Controller class for A_Projects
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class ProjectController
    {
        // Preload our schema..
        Project thisSchemaLoad = new Project();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public ProjectCollection FetchAll()
        {
            ProjectCollection coll = new ProjectCollection();
            Query qry = new Query(Project.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public ProjectCollection FetchByID(object Id)
        {
            ProjectCollection coll = new ProjectCollection().Where("ID", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public ProjectCollection FetchByQuery(Query qry)
        {
            ProjectCollection coll = new ProjectCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (Project.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (Project.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string ProjectNumber,string ProjectName,string HospitalClinicName,string ProjectLead,string ProjectType,string ProjectPhase,string ProjectActivity,string Location,int? PMUserID,int? SalespersonID,string PMAssigned,string DirectoryPath,string DirectoryPathExec,DateTime? Created,string WallDiagramFile,string CreatedBy,string UpdatedBy,DateTime? Updated,string Region,int? DesignDraftsmanID,string EngineeringConsultant,int? PhysicistID,int? AcceptedEstimateID)
	    {
		    Project item = new Project();
		    
            item.ProjectNumber = ProjectNumber;
            
            item.ProjectName = ProjectName;
            
            item.HospitalClinicName = HospitalClinicName;
            
            item.ProjectLead = ProjectLead;
            
            item.ProjectType = ProjectType;
            
            item.ProjectPhase = ProjectPhase;
            
            item.ProjectActivity = ProjectActivity;
            
            item.Location = Location;
            
            item.PMUserID = PMUserID;
            
            item.SalespersonID = SalespersonID;
            
            item.PMAssigned = PMAssigned;
            
            item.DirectoryPath = DirectoryPath;
            
            item.DirectoryPathExec = DirectoryPathExec;
            
            item.Created = Created;
            
            item.WallDiagramFile = WallDiagramFile;
            
            item.CreatedBy = CreatedBy;
            
            item.UpdatedBy = UpdatedBy;
            
            item.Updated = Updated;
            
            item.Region = Region;
            
            item.DesignDraftsmanID = DesignDraftsmanID;
            
            item.EngineeringConsultant = EngineeringConsultant;
            
            item.PhysicistID = PhysicistID;
            
            item.AcceptedEstimateID = AcceptedEstimateID;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,string ProjectNumber,string ProjectName,string HospitalClinicName,string ProjectLead,string ProjectType,string ProjectPhase,string ProjectActivity,string Location,int? PMUserID,int? SalespersonID,string PMAssigned,string DirectoryPath,string DirectoryPathExec,DateTime? Created,string WallDiagramFile,string CreatedBy,string UpdatedBy,DateTime? Updated,string Region,int? DesignDraftsmanID,string EngineeringConsultant,int? PhysicistID,int? AcceptedEstimateID)
	    {
		    Project item = new Project();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.ProjectNumber = ProjectNumber;
				
			item.ProjectName = ProjectName;
				
			item.HospitalClinicName = HospitalClinicName;
				
			item.ProjectLead = ProjectLead;
				
			item.ProjectType = ProjectType;
				
			item.ProjectPhase = ProjectPhase;
				
			item.ProjectActivity = ProjectActivity;
				
			item.Location = Location;
				
			item.PMUserID = PMUserID;
				
			item.SalespersonID = SalespersonID;
				
			item.PMAssigned = PMAssigned;
				
			item.DirectoryPath = DirectoryPath;
				
			item.DirectoryPathExec = DirectoryPathExec;
				
			item.Created = Created;
				
			item.WallDiagramFile = WallDiagramFile;
				
			item.CreatedBy = CreatedBy;
				
			item.UpdatedBy = UpdatedBy;
				
			item.Updated = Updated;
				
			item.Region = Region;
				
			item.DesignDraftsmanID = DesignDraftsmanID;
				
			item.EngineeringConsultant = EngineeringConsultant;
				
			item.PhysicistID = PhysicistID;
				
			item.AcceptedEstimateID = AcceptedEstimateID;
				
	        item.Save(UserName);
	    }
    }
}
