using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DAL
{
	/// <summary>
	/// Strongly-typed collection for the TakeoffInfo class.
	/// </summary>
    [Serializable]
	public partial class TakeoffInfoCollection : ActiveList<TakeoffInfo, TakeoffInfoCollection>
	{	   
		public TakeoffInfoCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TakeoffInfoCollection</returns>
		public TakeoffInfoCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TakeoffInfo o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the PM_TakeoffInfo table.
	/// </summary>
	[Serializable]
	public partial class TakeoffInfo : ActiveRecord<TakeoffInfo>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TakeoffInfo()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TakeoffInfo(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TakeoffInfo(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TakeoffInfo(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("PM_TakeoffInfo", TableType.Table, DataService.GetInstance("Internal"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "ID";
				colvarId.DataType = DbType.Int32;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = true;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				colvarId.DefaultSetting = @"";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarProjectID = new TableSchema.TableColumn(schema);
				colvarProjectID.ColumnName = "ProjectID";
				colvarProjectID.DataType = DbType.Int32;
				colvarProjectID.MaxLength = 0;
				colvarProjectID.AutoIncrement = false;
				colvarProjectID.IsNullable = true;
				colvarProjectID.IsPrimaryKey = false;
				colvarProjectID.IsForeignKey = false;
				colvarProjectID.IsReadOnly = false;
				colvarProjectID.DefaultSetting = @"";
				colvarProjectID.ForeignKeyTableName = "";
				schema.Columns.Add(colvarProjectID);
				
				TableSchema.TableColumn colvarDateCompleted = new TableSchema.TableColumn(schema);
				colvarDateCompleted.ColumnName = "DateCompleted";
				colvarDateCompleted.DataType = DbType.AnsiString;
				colvarDateCompleted.MaxLength = 0;
				colvarDateCompleted.AutoIncrement = false;
				colvarDateCompleted.IsNullable = true;
				colvarDateCompleted.IsPrimaryKey = false;
				colvarDateCompleted.IsForeignKey = false;
				colvarDateCompleted.IsReadOnly = false;
				colvarDateCompleted.DefaultSetting = @"";
				colvarDateCompleted.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDateCompleted);
				
				TableSchema.TableColumn colvarPm = new TableSchema.TableColumn(schema);
				colvarPm.ColumnName = "PM";
				colvarPm.DataType = DbType.AnsiString;
				colvarPm.MaxLength = 50;
				colvarPm.AutoIncrement = false;
				colvarPm.IsNullable = true;
				colvarPm.IsPrimaryKey = false;
				colvarPm.IsForeignKey = false;
				colvarPm.IsReadOnly = false;
				colvarPm.DefaultSetting = @"";
				colvarPm.ForeignKeyTableName = "";
				schema.Columns.Add(colvarPm);
				
				TableSchema.TableColumn colvarDrawingSet = new TableSchema.TableColumn(schema);
				colvarDrawingSet.ColumnName = "DrawingSet";
				colvarDrawingSet.DataType = DbType.AnsiString;
				colvarDrawingSet.MaxLength = 50;
				colvarDrawingSet.AutoIncrement = false;
				colvarDrawingSet.IsNullable = true;
				colvarDrawingSet.IsPrimaryKey = false;
				colvarDrawingSet.IsForeignKey = false;
				colvarDrawingSet.IsReadOnly = false;
				colvarDrawingSet.DefaultSetting = @"";
				colvarDrawingSet.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDrawingSet);
				
				TableSchema.TableColumn colvarSummary = new TableSchema.TableColumn(schema);
				colvarSummary.ColumnName = "Summary";
				colvarSummary.DataType = DbType.AnsiString;
				colvarSummary.MaxLength = -1;
				colvarSummary.AutoIncrement = false;
				colvarSummary.IsNullable = true;
				colvarSummary.IsPrimaryKey = false;
				colvarSummary.IsForeignKey = false;
				colvarSummary.IsReadOnly = false;
				colvarSummary.DefaultSetting = @"";
				colvarSummary.ForeignKeyTableName = "";
				schema.Columns.Add(colvarSummary);
				
				TableSchema.TableColumn colvarStatus = new TableSchema.TableColumn(schema);
				colvarStatus.ColumnName = "Status";
				colvarStatus.DataType = DbType.AnsiString;
				colvarStatus.MaxLength = 25;
				colvarStatus.AutoIncrement = false;
				colvarStatus.IsNullable = true;
				colvarStatus.IsPrimaryKey = false;
				colvarStatus.IsForeignKey = false;
				colvarStatus.IsReadOnly = false;
				colvarStatus.DefaultSetting = @"";
				colvarStatus.ForeignKeyTableName = "";
				schema.Columns.Add(colvarStatus);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["Internal"].AddSchema("PM_TakeoffInfo",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("ProjectID")]
		[Bindable(true)]
		public int? ProjectID 
		{
			get { return GetColumnValue<int?>(Columns.ProjectID); }
			set { SetColumnValue(Columns.ProjectID, value); }
		}
		  
		[XmlAttribute("DateCompleted")]
		[Bindable(true)]
		public string DateCompleted 
		{
			get { return GetColumnValue<string>(Columns.DateCompleted); }
			set { SetColumnValue(Columns.DateCompleted, value); }
		}
		  
		[XmlAttribute("Pm")]
		[Bindable(true)]
		public string Pm 
		{
			get { return GetColumnValue<string>(Columns.Pm); }
			set { SetColumnValue(Columns.Pm, value); }
		}
		  
		[XmlAttribute("DrawingSet")]
		[Bindable(true)]
		public string DrawingSet 
		{
			get { return GetColumnValue<string>(Columns.DrawingSet); }
			set { SetColumnValue(Columns.DrawingSet, value); }
		}
		  
		[XmlAttribute("Summary")]
		[Bindable(true)]
		public string Summary 
		{
			get { return GetColumnValue<string>(Columns.Summary); }
			set { SetColumnValue(Columns.Summary, value); }
		}
		  
		[XmlAttribute("Status")]
		[Bindable(true)]
		public string Status 
		{
			get { return GetColumnValue<string>(Columns.Status); }
			set { SetColumnValue(Columns.Status, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(int? varProjectID,string varDateCompleted,string varPm,string varDrawingSet,string varSummary,string varStatus)
		{
			TakeoffInfo item = new TakeoffInfo();
			
			item.ProjectID = varProjectID;
			
			item.DateCompleted = varDateCompleted;
			
			item.Pm = varPm;
			
			item.DrawingSet = varDrawingSet;
			
			item.Summary = varSummary;
			
			item.Status = varStatus;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varId,int? varProjectID,string varDateCompleted,string varPm,string varDrawingSet,string varSummary,string varStatus)
		{
			TakeoffInfo item = new TakeoffInfo();
			
				item.Id = varId;
			
				item.ProjectID = varProjectID;
			
				item.DateCompleted = varDateCompleted;
			
				item.Pm = varPm;
			
				item.DrawingSet = varDrawingSet;
			
				item.Summary = varSummary;
			
				item.Status = varStatus;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn ProjectIDColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn DateCompletedColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn PmColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn DrawingSetColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn SummaryColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn StatusColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"ID";
			 public static string ProjectID = @"ProjectID";
			 public static string DateCompleted = @"DateCompleted";
			 public static string Pm = @"PM";
			 public static string DrawingSet = @"DrawingSet";
			 public static string Summary = @"Summary";
			 public static string Status = @"Status";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
