using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DAL
{
    /// <summary>
    /// Controller class for URLTagVisits
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class URLTagVisitController
    {
        // Preload our schema..
        URLTagVisit thisSchemaLoad = new URLTagVisit();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public URLTagVisitCollection FetchAll()
        {
            URLTagVisitCollection coll = new URLTagVisitCollection();
            Query qry = new Query(URLTagVisit.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public URLTagVisitCollection FetchByID(object Id)
        {
            URLTagVisitCollection coll = new URLTagVisitCollection().Where("ID", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public URLTagVisitCollection FetchByQuery(Query qry)
        {
            URLTagVisitCollection coll = new URLTagVisitCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (URLTagVisit.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (URLTagVisit.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int Id,int Urlid,DateTime VisitDate,string ComputerName,bool? SynchedToLocal)
	    {
		    URLTagVisit item = new URLTagVisit();
		    
            item.Id = Id;
            
            item.Urlid = Urlid;
            
            item.VisitDate = VisitDate;
            
            item.ComputerName = ComputerName;
            
            item.SynchedToLocal = SynchedToLocal;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,int Urlid,DateTime VisitDate,string ComputerName,bool? SynchedToLocal)
	    {
		    URLTagVisit item = new URLTagVisit();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.Urlid = Urlid;
				
			item.VisitDate = VisitDate;
				
			item.ComputerName = ComputerName;
				
			item.SynchedToLocal = SynchedToLocal;
				
	        item.Save(UserName);
	    }
    }
}
